name = "lvgl_ada_simulator"
description = "Native simulator of an LVGL display"
version = "0.2.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

[[depends-on]]
asfml = "^2.5.3"
lvgl_ada = "0.2.0"
